# -*- coding: utf-8 -*-
"""Ejemplo CSV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p_EVkX9MvMixic-DjgEpGsu30IOy37cD
"""

#Importamos el módulo csv (En colab importamos un archivo)
#Importamos pandas
from google.colab import files
import csv
import pandas as pd

#Selector de archivos
#uploaded = files.upload()

# Obtener el filename
#calificaciones = list(uploaded.keys())[0]

"""
#Para leer un archivo

with open(calificaciones, mode="r") as file:

  #Creamos un objeto "reader"
  reader = csv.reader(file)

  #Para imprimir cada columna en el archivo
  for row in reader:
    print(row)
"""

"""
#Para Separar el encabezado

with open(calificaciones, mode="r") as file:

  #Creamos un objeto "reader"
  reader = csv.reader(file)

  header = next(reader)
  print("Encabezado:", header)

  #Para imprimir cada columna en el archivo
  for row in reader:
    print(row)
"""
"""
#Para leer como diccionario
with open(calificaciones, mode="r") as file:

  #Creamos un objeto "reader"
  reader = csv.DictReader(file)

  #Para imprimir cada columna en el archivo
  for row in reader:
    print(row)
"""
"""
#Para imprimir filas específicas
with open(calificaciones, mode="r") as file:

  #Creamos un objeto "reader"
  reader = list(csv.reader(file)) #Convertimos a lista

  #Para una columna en el archivo
  print("Flila 2:",reader[2]) #Tercera fila
"""
"""
#Para imprimir columnas específicas
with open(calificaciones, mode="r") as file:

  #Creamos un objeto "reader"
  reader = csv.reader(file)

  #Para una columna en el archivo
  for row in reader:
    print(row[0]) #Primera columna
"""
"""
#Para imprimir "celdas" específicas
with open(calificaciones, mode="r") as file:

  #Creamos un objeto "reader"
  reader = list(csv.reader(file))#Tomamos como lista

  print(reader[2][1]) #Fila 2, Columna 1
"""
"""
#Para usar con Pandas

df = pd.read_csv(calificaciones)

#Fila específica
#print(df.iloc[2])

#Columna específica
#print(df["Nombre"])

#Datos condicionados
#print(df[df["Calificación Final"]<=6])
"""
#Para editar un archivo
"""
with open("calificaciones2.csv", "w", newline="") as file:
    writer = csv.writer(file)

    # Encabezado
    writer.writerow(["Nombre", "Edad", "Parcial1"])

    # Filas
    writer.writerow(["Alicia", 95, "8"])
    writer.writerow(["Charly", 88, "9"])
    writer.writerow(["Héctor", 92, "6"])

#Creamos un objeto "reader"
with open("calificaciones2.csv", "r") as file:
  reader = csv.reader(file)

  #Para imprimir cada columna en el archivo
  for row in reader:
    print(row)

#Para agregar una línea
with open("Calificaciones2.csv", "a", newline="") as file:
    writer = csv.writer(file)

    writer.writerow(["David", 85, "7"])

with open("Calificaciones2.csv", "r", newline="") as file:
    reader = csv.reader(file)
    #Para imprimir cada columna en el archivo
    for row in reader:
      print(row)


#Agregar dato específico
nombre = "Emma"
edad = 90
parcial1 = "5"

with open("Calificaciones.csv", "a", newline="") as file:
    writer = csv.writer(file)
    writer.writerow([nombre, edad, parcial1])


with open("Calificaciones.csv", "r", newline="") as file:
    reader = csv.reader(file)
    print("\nContenido de Calificaciones.csv después de añadir a Emma:")
    for row in reader:
        print(row)

#Escribir múltiples filas en una lista

data = [
    ["Ana", 17, "9"],
    ["Luis", 18, "9"],
    ["Maria", 19, "10"]
]

with open("Calificaciones.csv", "a", newline="") as file:
    writer = csv.writer(file)
    writer.writerows(data)


with open("Calificaciones.csv", "r", newline="") as file:
    reader = csv.reader(file)
    print("\nContenido de Calificaciones.csv después de añadir múltiples filas:")
    for row in reader:
        print(row)
"""

