# -*- coding: utf-8 -*-
"""Línea recta.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HaKT1qp8I7ihTNGcFl-FoLUpyhnIkXTq
"""

import math
from sympy import symbols, Eq, solve

class Punto:
    """
    Clase que representa un punto en el plano cartesiano.

    Un punto se define como una pareja ordenada de números (x, y).
    """

    def __init__(self, x=0, y=0) :
        """
        Inicializa un punto con coordenadas x e y.
        """
        self.x = x
        self.y = y

    def get_x(self):
        """
        Devuelve la coordenada x del punto.
        """
        return self.x

    def get_y(self):
        """
        Devuelve la coordenada y del punto.
        """
        return self.y

    def suma(self, otro_punto: object) -> object:

        """
        Suma este punto con otro punto.

        Debe devolver un nuevo objeto Punto.
        """
        nuevo_punto = Punto(self.get_x() + otro_punto.get_x(),
                            self.get_y() + otro_punto.get_y())
        return nuevo_punto

    def resta(self, otro_punto: object) -> object:
        """
        Resta otro punto a este punto.

        Debe devolver un nuevo objeto Punto.
        """
        nuevo_punto = Punto(self.get_x() - otro_punto.get_x(),
                            self.get_y() - otro_punto.get_y())
        return nuevo_punto

    def desplazamiento(self, dx, dy):
        """
        Desplaza el punto actual sumando dx a x y dy a y.
        """
        nuevo_punto = Punto(self.get_x() + dx,
                            self.get_y() + dy)
        return nuevo_punto

    def distancia(self, otro_punto) ->float:
        """
        Calcula la distancia euclidiana entre este punto y otro punto.
        """
        #Punto 1 =  self
        #Punto2 =  otro_punto
        resta1 = otro_punto.get_x() - self.get_x()
        primer_cuadrado = resta1 * resta1
        resta2 = otro_punto.get_y() - self.get_y()
        segundo_cuadrado =  resta2 * resta2

        suma_cuadrados =  primer_cuadrado + segundo_cuadrado
        distancia = math.sqrt(suma_cuadrados)

        return distancia


    def __eq__(self, otro_punto):
        """
        Compara si dos puntos son iguales.

        Debe devolver True si tienen las mismas coordenadas.
        """
        # Validar que otro_punto sea un objeto de la clase Punto
        if isinstance(otro_punto,Punto):

        # Validar que las coordenadas sean iguales
            if self.get_x() == otro_punto.get_x() and self.get_y() == otro_punto.get_y():
                return True
            else:
                return False
        else:
            return False

    def __str__(self):
        """
        Devuelve el punto en formato (x, y).
        """
        return f"({self.x},{self.y})"

class Recta:
    """
    Clase que representa una recta en el plano cartesiano, definida por dos puntos.
    """

    def __init__(self, punto1: Punto, punto2: Punto):
        """
        Inicializa una recta con dos objetos Punto.
        """
        if not isinstance(punto1, Punto) or not isinstance(punto2, Punto):
            raise TypeError("Ambos argumentos deben ser objetos de la clase Punto")

        self.punto1 = punto1
        self.punto2 = punto2

    def pendiente(self) -> float:
        """
        Calcula la pendiente de la recta.

        Retorna None si la recta es vertical.
        """
        delta_x = self.punto2.get_x() - self.punto1.get_x()
        delta_y = self.punto2.get_y() - self.punto1.get_y()

        if delta_x == 0:
            return None  # Recta vertical
        return delta_y / delta_x

    def ecuacion(self) -> str:
        """
        Devuelve la ecuación de la recta.
        """
        m = self.pendiente()
        if m is None:
            return f"x = {self.punto1.get_x()}" # Vertical line
        else:
            return f"y - {self.punto1.get_y()} = {m} * (x - {self.punto1.get_x()})"

    def punto_pertenece_a_recta(self, punto: Punto) -> bool:
        """
        Verifica si un punto dado pertenece a la recta.
        """
        if not isinstance(punto, Punto):
            raise TypeError("El argumento debe ser un objeto de la clase Punto")

        m = self.pendiente()

        if m is None: # Recta vertical
            return punto.get_x() == self.punto1.get_x()
        else: # Recta no vertical
            # y - y1 = m * (x - x1)
            # Comprobamos si la ecuación se cumple para el punto dado
            y_diff = punto.get_y() - self.punto1.get_y()
            x_diff = punto.get_x() - self.punto1.get_x()
            return y_diff == m * x_diff

    def son_paralelas(self, otra_recta: 'Recta') -> bool:
        """
        Verifica si esta recta es paralela a otra recta.
        """
        if not isinstance(otra_recta, Recta):
            raise TypeError("El argumento debe ser un objeto de la clase Recta")

        m1 = self.pendiente()
        m2 = otra_recta.pendiente()

        if m1 is None and m2 is None: # Ambas son verticales
            return True
        elif m1 is None or m2 is None: # Una es vertical y la otra no
            return False
        else: # Ninguna es vertical, comparar pendientes
            return m1 == m2

    def son_perpendiculares(self, otra_recta: 'Recta') -> bool:
        """
        Verifica si esta recta es perpendicular a otra recta.
        """
        if not isinstance(otra_recta, Recta):
            raise TypeError("El argumento debe ser un objeto de la clase Recta")

        m1 = self.pendiente()
        m2 = otra_recta.pendiente()

        # Caso: Una es vertical y la otra horizontal
        if (m1 is None and m2 == 0) or (m2 is None and m1 == 0):
            return True
        # Caso: Ninguna es vertical
        elif m1 is not None and m2 is not None:
            # m1 * m2 = -1
            return m1 * m2 == -1
        else:
            return False # Una vertical y la otra no horizontal (o viceversa)

    def interseccion(self, otra_recta: 'Recta') -> Punto | None:
        """
        Calcula el punto de intersección entre esta recta y otra recta.

        Retorna un objeto Punto si hay un único punto de intersección,
        o None si las rectas son paralelas (incluyendo coincidentes).
        """
        if not isinstance(otra_recta, Recta):
            raise TypeError("El argumento debe ser un objeto de la clase Recta")

        x_sym, y_sym = symbols('x y')

        m1 = self.pendiente()
        m2 = otra_recta.pendiente()

        # Construye la ecuación para self (recta1)
        if m1 is None: # Línea vertical: x = x0
            eq1 = Eq(x_sym, self.punto1.get_x())
        else: # Línea no vertical: y - y0 = m(x - x0)
            eq1 = Eq(y_sym - self.punto1.get_y(), m1 * (x_sym - self.punto1.get_x()))

        # Construye la ecuación para otra_recta (recta2)
        if m2 is None: # Línea vertical: x = x0
            eq2 = Eq(x_sym, otra_recta.punto1.get_x())
        else: # Línea no vertical: y - y0 = m(x - x0)
            eq2 = Eq(y_sym - otra_recta.punto1.get_y(), m2 * (x_sym - otra_recta.punto1.get_x()))

        sol = solve([eq1, eq2], (x_sym, y_sym))

        if not sol: # Si no hay solución (Rectas paralelas y distintas)
            return None
        elif isinstance(sol, dict): # SymPy might return a dict directly for unique solution
            return Punto(float(sol[x_sym]), float(sol[y_sym]))
        elif isinstance(sol, list) and len(sol) == 1 and isinstance(sol[0], dict): # Si solamente hay una solución
            return Punto(float(sol[0][x_sym]), float(sol[0][y_sym]))
        else: # Si hay una infinidad de soluciones
            return None

    def __eq__(self, otra_recta: 'Recta') -> bool:
        """
        Compara si dos rectas son iguales.

        Devuelve True si tienen las mismas pendientes y al menos un punto en común.
        """
        if not isinstance(otra_recta, Recta):
            return False

        # Si son la misma instancia, son iguales
        if self is otra_recta:
            return True

        # Primero, comprueba si son paralelas
        if not self.son_paralelas(otra_recta):
            return False

        # Si son paralelas, comprueba si un punto de una recta pertenece a la otra
        return otra_recta.punto_pertenece_a_recta(self.punto1)

    def __str__(self):
        """
        Devuelve la recta en formato 'Recta entre (x1,y1) y (x2,y2)'.
        """
        return f"Recta entre {self.punto1} y {self.punto2}"

"""
La abstracción se usa al definir una recta como dos puntos. Dichos puntos
nos permiten calcular todo lo que hemos calculado sin necesidad de una construcción
más complicada. La encapsulación la hicimos a través de los métodos y atributos
de la clase.
"""


#Primera recta:
punto1 = Punto(3,7)
punto2 = Punto(67,83)
recta1 = Recta(punto1,punto2)

#Segunda recta:
punto3 = Punto(-3,8)
punto4 = Punto(0,5)
recta2 = Recta(punto3,punto4)

#Eje Y:
punto5 = Punto(0,0)
punto6 = Punto(0,1)
ejeY = Recta(punto5,punto6)

#Propiedades de la primera recta:
print("1-Ecuación:", recta1.ecuacion())
print("1-Pendiente:", recta1.pendiente())
print("Punto pertenece a recta:",recta1.punto_pertenece_a_recta(punto1))
print("Punto pertenece a recta:",recta1.punto_pertenece_a_recta(Punto(4,6)))
print("Recta 1 está dada por:", recta1.__str__())
print("La ordenada al origen es:",recta1.interseccion(ejeY))

#Comparación entre ambas rectas:
print("1 y 2 paralelas:", recta1.son_paralelas(recta2))
print("1 y 2 perpendiculares:", recta1.son_perpendiculares(recta2))
print("1 y 2 Intersección:", recta1.interseccion(recta2))
print("1 y 2 son iguales:", recta1.__eq__(recta2))