# -*- coding: utf-8 -*-
"""segundo ejercicio de la tarea 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RKM-pfujc3OhrBg1oX8erGknjdcxy0Op
"""



class NumeroComplejo:
    """
    Clase que representa un número complejo de la forma a + bi.
    """
    def __init__(self, real, imaginario):
        """
        Inicializa un número complejo.

        :param real: Parte real
        :param imaginario: Parte imaginaria
        """
        self.real = real
        self.imaginario = imaginario

    def sumar(self, otro):
        """
        Suma dos números complejos.
        """
        return NumeroComplejo(
            self.real + otro.real,
            self.imaginario + otro.imaginario
        )

    def restar(self, otro):
        """
        Resta dos números complejos.
        """
        return NumeroComplejo(
            self.real - otro.real,
            self.imaginario - otro.imaginario
        )

    def multiplicar(self, otro):
        """
        Multiplica dos números complejos.
        """
        real = self.real * otro.real - self.imaginario * otro.imaginario
        imaginario = self.real * otro.imaginario + self.imaginario * otro.real
        return NumeroComplejo(real, imaginario)

    def dividir(self, otro):
        """
        Divide dos números complejos.
        Encuentra el denominador, para despues dividir la parte real
        y la imaginaria
        """
        denominador = otro.real ** 2 + otro.imaginario ** 2
        real = (self.real * otro.real + self.imaginario * otro.imaginario) / denominador
        imaginario = (self.imaginario * otro.real - self.real * otro.imaginario) / denominador
        return NumeroComplejo(real, imaginario)

    def __eq__(self,otro):
        """
        Compara si dos numeros complejos son iguales
        """
        if self.real == otro.real and self.imaginario == otro.imaginario:
            return "Ambos numeros complejos son iguales"
        else:
            return "Los numeros complejos son diferentes"

    def __str__(self):
        """
        Representación de cadena del número complejo.
        """
        if self.imaginario >= 0:
            return f"{self.real} + {self.imaginario}i"
        else:
            return f"{self.real} - {abs(self.imaginario)}i"


print("Bienvenido a la calculadora de numeros complejos")
print("Instrucciones: Escoge la opción que desees, al momento que te pida las variables")
print("solo debes poner el numero real y el programa hara lo suyo :)")
print("Comencemos")
while True:
  print("\n[0] SALIR")
  print("[1] Suma")
  print("[2] Resta")
  print("[3] Multiplicar")
  print("[4] Dividir")
  print("[5] Comparar")
  print("Elige una opción: ")
  opcion = int(input())

  match opcion:
    case 0:
      print("Saliendo...")
      break

    case 1:
      print("Ingresa el primer numero complejo:")
      real1 = float(input("Parte real del primer numero: "))
      Imaginario1 = float(input("Parte Imaginaria del primer numero: "))
      real2 = float(input("Parte real del primer numero: "))
      Imaginario2 = float(input("Parte Imaginaria del primer numero: "))

      numero1 = NumeroComplejo(real1,Imaginario1)
      numero2 = NumeroComplejo(real2,Imaginario2)
      Resultado = numero1.sumar(numero2)
      print(f"El resultado de sumar los numeros complejos es: {Resultado}")

    case 2:
      print("Ingresa el primer numero complejo:")
      real1 = float(input("Parte real del primer numero: "))
      Imaginario1 = float(input("Parte Imaginaria del primer numero: "))
      real2 = float(input("Parte real del prime4r numero: "))
      Imaginario2 = float(input("Parte Imaginaria del primer numero: "))

      numero1 = NumeroComplejo(real1,Imaginario1)
      numero2 = NumeroComplejo(real2,Imaginario2)
      Resultado = numero1.restar(numero2)
      print(f"El resultado de restar los numeros complejos es: {Resultado}" )

    case 3:
      print("Ingresa el primer numero complejo:")
      real1 = float(input("Parte real del primer numero: "))
      Imaginario1 = float(input("Parte Imaginaria del primer numero: "))
      real2 = float(input("Parte real del primer numero: "))
      Imaginario2 = float(input("Parte Imaginaria del primer numero: "))

      numero1 = NumeroComplejo(real1,Imaginario1)
      numero2 = NumeroComplejo(real2,Imaginario2)
      Resultado = numero1.multiplicar(numero2)
      print(f"El resultado de multiplicar los numeros complejos es: {Resultado}")

    case 4:
      print("Ingresa el primer numero complejo:")
      real1 = float(input("Parte real del primer numero: "))
      Imaginario1 = float(input("Parte Imaginaria del primer numero: "))
      real2 = float(input("Parte real del primer numero: "))
      Imaginario2 = float(input("Parte Imaginaria del primer numero: "))

      numero1 = NumeroComplejo(real1,Imaginario1)
      numero2 = NumeroComplejo(real2,Imaginario2)
      Resultado = numero1.dividir(numero2)
      print(f"El resultado de dividir los numeros complejos es: {Resultado}")

    case 5:
      print("Ingresa el primer numero complejo:")
      real1 = float(input("Parte real del primer numero: "))
      Imaginario1 = float(input("Parte Imaginaria del primer numero: "))
      real2 = float(input("Parte real del primer numero: "))
      Imaginario2 = float(input("Parte Imaginaria del primer numero: "))

      numero1 = NumeroComplejo(real1,Imaginario1)
      numero2 = NumeroComplejo(real2,Imaginario2)
      Comparacion = numero1.__eq__(numero2)
      print(f"¿Son iguales?: {Comparacion}" )

    case _:
      print("opción no valida")


  """
    El encapsulamiento esta en crear la clase, cuando creamos la clase todo lo que pertenece a esta,
    se queda ahi, en lugar de tener operaciones sueltas, todo se agrupa en esa clase.

    La abstracción esta presente cuando se hacen las operaciones, por ejemplo en el str el usuario
    no sabe que hay detrás de como se escribio el formato del numero complejo, otro ejemplo es en la suma
    donde el usuario solo da los valores y no sabe como tal que esta haciendo la calculadora

  """