# -*- coding: utf-8 -*-
"""P1_EJ2_MGG

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bs7axrs97M1egWEBVjDIDXeP86NOYwpZ
"""

def procesar_venta():
  print("registro de ventas")

  #1 Entrada de datos
  nombre_vendedor = input("Nombre del vendedor")
  clave_del_producto=input("Clave del producto")

  #Validacion de cantidad (Entero positivo)
  cantidad_vendida=int(input("Cantidad vendida"))
  if cantidad_vendida <= 0:
    print("error, la cantidad debe ser un entero positivo")
    return
  #Validacion de precio (Flotante positivo)
  precio_unitario=float(input("Precio unitario"))
  if precio_unitario <= 0:
    print("error, el precio debe ser un flotante positivo")
    return

  tipo_de_cliente=input("Tipo de cliente (nuevo/frecuente)").lower()
  # 2. Calculos
  subtotal=cantidad_vendida*precio_unitario

  #Logica de descuento 10% si es frecuente
  if tipo_de_cliente == "frecuente":
    descuento=subtotal*0.1
  total_pagar= subtotal-descuento

  #resumen de resultados
  print("Resumen de ventas")
  print("Vendedor:", nombre_vendedor)
  print("Clave del producto:", clave_del_producto)
  print("Cantidad vendida:", cantidad_vendida)
  print("Precio unitario:", precio_unitario)
  print("Subtotal:", subtotal)
  print("Descuento:", descuento)
  print("Total a pagar:", total_pagar)

#Ejecutar funcion procesar_venta()

procesar_venta()