# -*- coding: utf-8 -*-
"""P1_Ej1_MGG

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19K9y_InHrUGIXKVm6w0hJyUNlATkOziB
"""

import math
import cmath # Import cmath for complex number operations

def resolver_cuadratica():
  print("Calculadora de ecuación cuadrática (ax2 + bx + c = 0)")

  #Solicitar los coeficientes al usuario con a distinto de 0
  a = float(input("ingrese el valor de a (recuerda que debe de ser distinto a 0)"))
  b = float(input("ingrese el valor de b"))
  c = float(input("ingrese el valor de c"))

  # 1. Verificar que a sea distinto a 0
  if a == 0:
    print("quedamos que a no podia ser 0, vuelve a empezar")
  else:
    # 2.Calcular el discriminante D = b2 - 4ac
    discriminante = (b**2) - (4 * a * c)
    print(f"El discriminante es: {discriminante}")

    # 3. Validar el discriminante para calcular las raíces
    if discriminante > 0:
      raiz_cuadrada = math.sqrt(discriminante)
      x1 = (-b + raiz_cuadrada) / (2*a)
      x2 = (-b - raiz_cuadrada) / (2*a)
      print("Las raíces realeS son:")
      print(f"x1 = {x1}")
      print(f"x2 = {x2}")
    elif discriminante == 0:
      print("Este programa solo resuelve discriminantes positivos, vuelve a empezar")
    else: # discriminante < 0
      print("este programa solo resuelve discriminantes positivos vuelve a empezar")
    print("GRACIAS POR USAR MI PROGRAMA JIJI")
    #Ejecutar función resolver_cuadratica(0)

resolver_cuadratica()

