# -*- coding: utf-8 -*-
"""Copia de Tarea_2_cajero_automático.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bzWjUrgJr7FEphwM3eGLT6asFkyAxlDR
"""

#Se define la clase "Cajero",y se inicializa, así como cuatro funciones diferentes.
class Cajero:
  def __init__(self, balance=0):
    self.balance = balance

  def consultar_saldo(self):
    return f"El balance de tu cuenta es: (MXN) {self.balance}"
#No perimtimos que se agregue una cantidad de dinero negativa.
  def depositar(self, amount):
    if amount >= 0:
      self.balance += amount
      return f"(MXN){amount} fue depositado a tu cuenta. Tu saldo actual es: (MXN) {self.balance}"
    else:
      return "Monto inválido"
#No permitimos que se pueda retirar más dinero que el dinero que se tiene.
  def retirar(self, amount):
    if amount <= self.balance:
      self.balance -= amount
      return f"(MXN) {amount} fue retirado de tu cuenta. Balance actual: (MXN) {self.balance}"
    else:
      return "Saldo insuficiente"

cajero = Cajero()

#Se define un menú y se imprime, para así poder dar opciones al usuario

menu = """
Bienvenida al cajero automático del banco. ¿Qué operación deseas realizar?

1: Consultar saldo
2: Depositar dinero
3: Retirar dinero
4: Salir
"""
print(menu)

#Se usa while para poder ejecutar el código hasta que el usuario lo desee.
#Rompemos el while si se selecciona la opción de salir. Para cada opción ejecutamos alguna de las cuatro funciones antes definidas.

while True:

  operacion = input("Ingresa la operación que deseas realizar (1/2/3/4): ")

  if operacion == "1":
    print(cajero.consultar_saldo())
  elif operacion == "2":
    amount = float(input("Ingresa la cantidad de dinero que deseas depositar (MXN): "))
    print(cajero.depositar(amount))
  elif operacion == "3":
    amount = float(input("Ingresa la cantidad de dinero que deseas retirar (MXN): "))
    print(cajero.retirar(amount))
  elif operacion == "4":
    print("Gracias por hacer uso de este cajero, buen día.")
    break
  else:
    print("Opción inválida") #En caso de que no se eliga ningún número del uno al cuatro

