# -*- coding: utf-8 -*-
"""Tarea 2, ejercicios 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mQF64BqF7W7-RZhDuGfVui7IpcOTvz3T
"""

# @title Código de la tarea (picar en la ">" para ver código)
import random

def dado(): #Calcula dos numeros obtenidos por un dado
  resultado_1 = int(random.randint(1,6))
  print(f"Número 1: {resultado_1}")
  resultado_2 = int(random.randint(1,6))
  print(f"Número 2: {resultado_2}")
  Producto = resultado_1 * resultado_2
  return Producto

def verificar_multiplo():#Verifica si es multiplo de 10, 5, 2 o ninguno de estos
  numero = dado()
  if numero % 10 == 0:#Usamos 10 por que los multiplos de 10 son los que te hacen perder y simplifica las cosas
    return False
  elif numero % 2 == 0:
    return True
  elif numero % 5 == 0:
    return True
  else:
    return False

def dado_2():#Es el segundo dado por si llega a existir un empate, muestra 2 resultados nuevos, uno para el jugador y otro para la computadora
  numero_dado = int(random.randint(1,6))
  return numero_dado

menu = True #Empezamos a construir el menú que va a contar con dos opciones.
while menu: #Ponemos las opciones
  print("\n¡Bienvenido a jugando contra la computadora!")
  print("Elige una opción para poder comenzar a jugar:")
  print("1. Jugar")
  print("2. Salir")
  opcion = input("Ingresa el número de la opción que deseas: ")

  if opcion == "1":#Si escoje 1, le preguntara si esta listo para jugar
    while True:
      print("\n¡Hora de jugar!")
      print("Instrucciones: Lanzaras un dado y con base a eso se definira si ganaste o perdiste contra la compu.\nGanaras si obtienes un numero multiplo de 2 o 5, pero OJO no debe ser multiplo de ambos a la vez.")
      print("¿LISTO? S/N")
      respuesta = input("Ingresa tu respuesta: ")

      if respuesta.upper() == "S":#Si escoje s, entonces el programa se ejecuta
        print("¡Comencemos!")
        print("\nTus números son: ")
        Usuario = verificar_multiplo()#Llamamos a la función para ver si el producto de los numeros es multiplo de 2 o 5
        print("\nLa computadora tiene los siguientes números: ")
        Computadora = verificar_multiplo()#Llamamos a la función para ver si el producto de los numeros es multiplo de 2 o 5

        """Esta es la parte en donde compara los resultados del usuario y computadora,
        asi mismo, valida si son multiplos de 5 o 2 o de ambos."""
        if Usuario == True and Computadora == True:
          print("EMPATE")
          print("\nDado que hay un empate se vuelve a lanzar el dado")
          Usuario_1 = dado_2()
          print(f"Tu número es: {Usuario_1}")
          Computadora_1 = dado_2()
          print(f"La computadora tiene: {Computadora_1}")
          if Usuario_1 > Computadora_1:#Si existe un empate, se activa esta parte del código,
            print("GANA JUGADOR")
          elif Usuario_1 < Computadora_1:
            print("GANA COMPUTADORA")
          else:
            print("Nadie gana")#Aquí termina el proceso si existe un empate

        elif Usuario == True and Computadora == False:
          print("Gana Jugador")
        elif Usuario == False and Computadora == True:
          print("Gana computadora")
        else:
          print("Nadie gana")#Aqui termina el proceso del juego contra la computadora

      elif respuesta.upper() == "N":#Si escoge la opción N, lo regresa al menú, e igual termina esta parte del proceso
        print("OUH, una lástima regresa cuando estes listo.")
        break
      else:#Te pide que ingreses una respuesta valida
        print("Respuesta no válida. Por favor, ingresa 'S' o 'N'.")

  elif opcion == "2":#Te saca del juego si escoges la opción 2
    print("¡Gracias por jugar! ¡Hasta luego!")
    menu = False
    break
  else:#Te pide que ingreses una respuesta valida
    print("Opción no válida. Por favor, elige una opción válida.")

# @title Código para el diagrama de flujo y la imagen del diagrama de flujo
import graphviz

# Crear el diagrama de flujo detallado
dot = graphviz.Digraph('G', comment='Diagrama Detallado Juego Dados')
dot.attr(rankdir='TB', size='10,14')

# Estilos de nodos
dot.attr('node', shape='ellipse', style='filled', color='#D5E8D4')
dot.node('start', 'Inicio')
dot.node('end', 'Fin')

dot.attr('node', shape='diamond', style='filled', color='#FFF2CC')
dot.node('menu', '¿Menú: Jugar (1)?')
dot.node('listo', '¿Listo? (S/N)')
dot.node('mod10', '¿Producto es\nmúltiplo de 10?') # Primer filtro
dot.node('mod25', '¿Producto es\nmúltiplo de 2 o 5?') # Segundo filtro
dot.node('ver_empate', '¿Jugador y Compu\nson True?') # Condición de empate

dot.attr('node', shape='box', style='filled', color='#F5F5F5')
dot.node('lan_dados', 'Función dado()\n(Lanzar 2 dados,\ncalcular producto)')
dot.node('res_multiplo', 'verificar_multiplo()\nRetorna True/False')
dot.node('lan_desempate', 'Función dado_2()\n(Desempate, gana el mayor)')

dot.attr('node', shape='parallelogram', style='filled', color='#DAE8FC')
dot.node('input_m', 'Leer Opción Menú')
dot.node('print_win', 'Mostrar Ganador\no "Nadie Gana"')

# Conexiones
dot.edge('start', 'input_m')
dot.edge('input_m', 'menu')
dot.edge('menu', 'end', label='2')
dot.edge('menu', 'listo', label='1')

dot.edge('listo', 'input_m', label='N')
dot.edge('listo', 'lan_dados', label='S')

dot.edge('lan_dados', 'res_multiplo')
dot.edge('res_multiplo', 'mod10')

# Detalle de la función verificar_multiplo()
dot.edge('mod10', 'ver_empate', label='Sí (Nadie gana el tiro)\nRetorna False')
dot.edge('mod10', 'mod25', label='No')

dot.edge('mod25', 'ver_empate', label='Sí (Jugador cumple regla)\nRetorna True')
dot.edge('mod25', 'ver_empate', label='No (Nadie gana el tiro)\nRetorna False')

# Lógica del ganador/empate (Punto de tu pregunta)
dot.edge('ver_empate', 'print_win', label='Uno es True, Uno es False')
dot.edge('ver_empate', 'print_win', label='Ambos son False\n(Caso M10 o Ninguno)')
dot.edge('ver_empate', 'lan_desempate', label='Ambos son True\n(Empate a resolver)')

dot.edge('lan_desempate', 'print_win')
dot.edge('print_win', 'listo') # Volver a preguntar si está listo

# Visualizar
dot